name: 📦 Build 📦

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    name: Build Site
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install Deps & Build
        continue-on-error: true
        run: |
          npm i -g pnpm
          pnpm install
          pnpm build
        working-directory: web

      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          name: thisisabuild
          path: ./web/dist/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    name: Deploy Site
    runs-on: ubuntu-latest

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: thisisabuild
          path: ./build

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

    # - name: Deploy
    #   continue-on-error: true
    #   uses: cloudflare/wrangler-action@v3
    #   with:
    #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    #     command: pages deploy ./web/dist --project-name=pkgs.pkgforge.dev
    #     gitHubToken: ${{ secrets.GITHUB_TOKEN }}
