name: 📦 Mock Build 📦

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install Deps & Build
        continue-on-error: true
        run: |
          npm i -g pnpm
          pnpm install
          pnpm build
        working-directory: web

      - name: Upload site
        uses: actions/upload-artifact@v4
        with:
          compression-level: 9
          path: ./web/dist/

      - name: Upload doc
        uses: actions/upload-artifact@v4
        with:
          compression-level: 9
          path: ./web/src/

    # - name: Deploy
    #   continue-on-error: true
    #   uses: cloudflare/wrangler-action@v3
    #   with:
    #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    #     command: pages deploy ./web/dist --project-name=pkgs.pkgforge.dev
    #     gitHubToken: ${{ secrets.GITHUB_TOKEN }}
